// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_total_number_of_broken = "CgkIk5zJ6IMPEAIQBQ"; // <GPGSID>
        public const string achievement_king_of_destruction_of_rice_cake = "CgkIk5zJ6IMPEAIQAw"; // <GPGSID>
        public const string achievement_first_punch = "CgkIk5zJ6IMPEAIQAQ"; // <GPGSID>
        public const string achievement_doctor_of_rabbt = "CgkIk5zJ6IMPEAIQBA"; // <GPGSID>
        public const string achievement_messiah_in_the_rabbit_world = "CgkIk5zJ6IMPEAIQAg"; // <GPGSID>
        public const string leaderboard_maximum_number_of_broken = "CgkIk5zJ6IMPEAIQAA"; // <GPGSID>

}

